version: '3'
services:
  db1:
    image: mysql:5.7
    volumes:
      - db1_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_wordpress_password
  redis1:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass your-redis-password-here --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    volumes:
      - redis1_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  wordpress1:
    depends_on:
      - db1
      - redis1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress1_content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db1:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: your_wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis configuration */
        define('WP_REDIS_HOST', 'redis1');
        define('WP_REDIS_PORT', '6379');
        define('WP_REDIS_PASSWORD', 'your-redis-password-here');
        define('WP_CACHE_KEY_SALT', 'your-unique-salt-here');
        define('WP_CACHE', true);
      REDIS_HOST: redis1
  nginx:
    image: nginx:latest
    restart: always
    depends_on:
      - wordpress1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
  db2:
    image: mysql:5.7
    volumes:
      - db2_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: your_wordpress_password
  redis2:
    image: redis:latest
    restart: always
    entrypoint: redis-server --appendonly yes --requirepass your-redis-password-here --maxmemory 512mb --maxmemory-policy allkeys-lru
    ports:
      - "6379"
    volumes:
      - redis2_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  wordpress2:
    depends_on:
      - db2
      - redis2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - wordpress2_content:/var/www/html/wp-content
    restart: always
    environment:
      WORDPRESS_DB_HOST: db2:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: your_wordpress_password
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis configuration */
        define('WP_REDIS_HOST', 'redis2');
        define('WP_REDIS_PORT', '6379');
        define('WP_REDIS_PASSWORD', 'your-redis-password-here');
        define('WP_CACHE_KEY_SALT', 'your-unique-salt-here');
        define('WP_CACHE', true);
      REDIS_HOST: redis2
volumes:
  db1_data:
  wordpress1_content:
  redis1_data:
  db2_data:
  wordpress2_content:
  redis2_data:
