version: '3'

services:
  mon:
    image: ceph/ceph:v16.2.5
    command: mon
    environment:
      - MON_IP=172.16.238.10
      - CEPH_PUBLIC_NETWORK=172.16.238.0/24
      - CEPH_CLUSTER_NETWORK=172.16.238.0/24
    volumes:
      - ceph-config:/etc/ceph
      - ceph-data:/var/lib/ceph
    ports:
      - "6789:6789"
    networks:
      - ceph-net

  mgr:
    image: ceph/ceph:v16.2.5
    command: mgr
    volumes:
      - ceph-config:/etc/ceph
      - ceph-data:/var/lib/ceph
    networks:
      - ceph-net

  osd:
    image: ceph/ceph:v16.2.5
    command: osd
    environment:
      - OSD_FORCE_ZAP=1
      - OSD_DEVICE=/dev/sdb
      - OSD_TYPE=disk
    volumes:
      - ceph-config:/etc/ceph
      - ceph-data:/var/lib/ceph
      - /dev:/dev
    networks:
      - ceph-net

volumes:
  ceph-config:
  ceph-data:

networks:
  ceph-net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
