---
- name: Install MySQL and create database
  hosts: webservers
  become: yes
  become_method: sudo
  vars:
    mysql_root_password: yourpassword

  tasks:
    - name: Install MySQL
      apt:
        name: mysql-server
        state: present

    - name: Install pip for Python 3
      apt:
        name: python3-pip
        state: present

    - name: Install Python 3 development headers
      apt:
        name: python3-dev
        state: present

    - name: Install MySQL development headers
      apt:
        name: libmysqlclient-dev
        state: present

    - name: Install MySQL client library
      apt:
        name: python3-mysqldb
        state: present

    - name: Set MySQL root password
      mysql_user:
        login_user: root
        login_password: ""
        user: root
        password: "{{ mysql_root_password }}"
        host: localhost
        update_password: always
        check_implicit_admin: yes
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Create database
      mysql_db:
        login_host: localhost
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: test
        state: present

    - name: Show database list
      mysql_db:
        login_host: localhost
        login_user: root
        login_password: "{{ mysql_root_password }}"
        state: list
