---
- name: Install Apache on Ubuntu
  hosts: webservers
  become: true
  become_method: sudo

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Enable Apache service
      systemd:
        name: apache2
        enabled: yes
