---
- name: Change DNS resolver configuration and ping 8.8.8.8 from webservers
  hosts: webservers
  become: yes
  become_method: sudo

  tasks:
    - name: Update resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Ping 8.8.8.8
      ping:
        dest: 8.8.8.8
