---
- name: Change DNS resolver configuration and ping 8.8.8.8 from webservers
  hosts: webservers
  become: yes
  become_method: sudo

  tasks:
    - name: Update resolv.conf
      template:
        src: resolv.conf.j2
        dest: /etc/resolv.conf

    - name: Ping 8.8.8.8
      shell: ping -c 1 -w 1 8.8.8.8 > /dev/null && echo "Success" || echo "Failure"
      register: ping_result

    - name: Display ping result
      debug:
        var: ping_result.stdout_lines[0]
